name: Deployment
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deployment
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          command_timeout: 3m
          script: |
                  cd Dotsimus
                  pm2 stop lib/index.js
                  echo app stopped
                  git pull
                  pm2 start lib/index.js
                  echo done
